language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t regisrampasso/docker-react -f Dockerfile.dev .
script:
      - docker run -e CI=true regisrampasso/docker-react npm run test

#deploy:
#  provider: elasticbeanstalk
#  region: ""
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: ""
#  bucket_path: "docker-react"
#  on:
#    branch: master